require("core.plugin_config.mason")
require("core.plugin_config.gruvbox")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.autopairs")
require("core.plugin_config.lsp_config")
